FROM openjdk:8


COPY . /project
#run the spring boot application
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom", "-Dblabla", "-jar","/project/target/demo-0.0.1-SNAPSHOT.jar"]


#this part for debug is moved into compose file, into "command":
#ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/project/target/demo-0.0.1-SNAPSHOT.jar"]


